default_language_version:
    python: python3.12

repos:
  # All files basic formatter
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        exclude: "docs/mkdocs.yml"
      - id: end-of-file-fixer
        exclude: "src/spec/configs/\\w+\\.yaml$"
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-format
      - id: ruff-check
        exclude: "scripts/.*\\.py$"
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
    -   id: mypy
        exclude: "scripts/.*\\.py$"
        additional_dependencies:
          [
          aiohttp==3.14.2,
          aiosignal==1.4.0,
          msgspec==0.21.1,
          prometheus-client==0.25.0,
          pytest==9.1.1,
          "spy-ssz @ git+https://github.com/eth2353/spy-ssz.git@56a889b4bcb25a2e471fccbd282c60cbc2e39529",
          types-PyYAML==6.0.12.20260518,
          ]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args: ["--failure-threshold=warning"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.32
    hooks:
      - id: uv-lock
      - id: uv-export
        name: export dependencies -> requirements.txt
        args: ["--no-dev", "--output-file=requirements.txt"]
      - id: uv-export
        name: export dev dependencies -> requirements-dev.txt
        args: ["--dev", "--output-file=requirements-dev.txt"]

  - repo: local
    hooks:
      - id: check-spec-types
        name: check types used in spec
        entry: ./src/spec/type_check.sh
        language: system
