{
 "title": "Vero - Simple",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vero_info,instance)"
    }
   },
   {
    "name": "beacon_node_host",
    "label": "Beacon Node",
    "query": {
     "query": "label_values(requests_created{service_type=\"beacon_node\", instance=\"$instance\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Published blocks [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_blocks_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published attestations [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_attestations_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published sync messages [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_sync_committee_messages_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published aggregate attestations [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_aggregate_attestations_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published sync contributions [1h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_published_sync_committee_contributions_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head Events Processed [$__interval]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "round(increase(vc_processed_beacon_node_events_total{event_type=~\"(HeadEvent|HeadV2Event)\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_status{instance=\"$instance\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Attestation Consensus Failures [1h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(vc_attestation_consensus_failures_total{instance=\"$instance\"}[1h]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slashing Detection Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slashing_detected{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors [1h]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(errors_total{instance=\"$instance\"}[1h]) and on(instance, job) vero_info))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vero_info{instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Beacon Node Score",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "beacon_node_score{instance=\"$instance\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}