participants:
  - el_type: nethermind
    cl_type: lodestar
    supernode: true
    use_separate_vc: true
    vc_type: vero
    vc_image: vero:custom
    use_remote_signer: true

network_params:
  fulu_fork_epoch: 1
  slot_duration_ms: 3000

additional_services:
  - assertoor

assertoor_params:
  run_stability_check: true
  run_block_proposal_check: true
