from spec.common import Uint64

INTERVALS_PER_SLOT = 3
TARGET_AGGREGATORS_PER_COMMITTEE = Uint64(2**4)
TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE = Uint64(2**4)
SYNC_COMMITTEE_SUBNET_COUNT = Uint64(2**2)
