from remerkleable.basic import uint64

TARGET_AGGREGATORS_PER_COMMITTEE = uint64(2**4)
TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE = uint64(2**4)
SYNC_COMMITTEE_SUBNET_COUNT = uint64(2**2)
BYTES_PER_FIELD_ELEMENT = uint64(2**5)
DEPOSIT_CONTRACT_TREE_DEPTH = uint64(2**5)
