name: Docker - build & push

on:
  push:
    branches: [ "master" ]
    tags: [ v* ]

jobs:
  verify-configs:
    uses: ./.github/workflows/verify-configs.yml

  build-and-push:
    # This depends on the verify-configs job above
    needs: verify-configs

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # The permissions below are needed
      # only for generating attestations
      id-token: write
      attestations: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Docker metadata
      id: docker_metadata
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # reflects the last commit on the `master` branch
          type=ref,event=branch
          # tags release images as vX.Y.Z
          # tags _only_ stable releases as `latest`
          type=semver,pattern={{version}},prefix=v

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: build_and_push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        build-args: |
          GIT_TAG=${{ github.ref_name }}
          GIT_COMMIT=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}

    - name: Generate build provenance attestation
      uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build_and_push.outputs.digest }}
        push-to-registry: true

    - name: Generate SBOM
      uses: anchore/sbom-action@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0.20.6
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        output-file: 'sbom.json'

    - name: Generate SBOM attestation
      uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build_and_push.outputs.digest }}
        sbom-path: 'sbom.json'
        push-to-registry: true
