name: Docker - build & push

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "master" ]
    tags: [ v* ]

jobs:
  verify-configs:
    uses: ./.github/workflows/verify-configs.yml

  build-and-push:
    # This depends on the verify-configs job above
    needs: verify-configs

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: docker_metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/vero
        tags: |
          type=ref,event=branch
          type=ref,event=tag

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          GIT_TAG=${{ github.ref_name }}
          GIT_COMMIT=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
