name: Docker - build & push

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "master" ]
    tags: [ v* ]

jobs:
  verify-configs:
    uses: ./.github/workflows/verify-configs.yml

  build-and-push:
    # This depends on the verify-configs job above
    needs: verify-configs

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Docker metadata
      id: docker_metadata
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      with:
        images: ghcr.io/${{ github.repository_owner }}/vero
        tags: |
          # reflects the last commit on the `master` branch
          type=ref,event=branch
          # tags release images as vX.Y.Z
          # tags _only_ stable releases as `latest`
          type=semver,pattern={{version}},prefix=v

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        build-args: |
          GIT_TAG=${{ github.ref_name }}
          GIT_COMMIT=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
