name: Docker - build & push

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
    tags: [ v* ]

jobs:
  verify-spec-values:
    uses: ./.github/workflows/verify-spec-values.yml

  build-and-push:
    # Ensure spec values are up-to-date before building an image
    needs: verify-spec-values

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # The permissions below are needed
      # only for generating attestations
      id-token: write
      attestations: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Docker metadata
      id: docker_metadata
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # reflects the last commit on the `master` branch
          type=ref,event=branch
          # tags release images as vX.Y.Z
          # tags _only_ stable releases as `latest`
          type=semver,pattern={{version}},prefix=v

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: build_and_push
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        build-args: |
          GIT_TAG=${{ github.ref_name }}
          GIT_COMMIT=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}

    - name: Generate build provenance attestation
      uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build_and_push.outputs.digest }}
        push-to-registry: true

    - name: Generate SBOM
      uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        output-file: 'sbom.json'
        upload-release-assets: false

    - name: Generate SBOM attestation
      uses: actions/attest-sbom@c604332985a26aa8cf1bdc465b92731239ec6b9e # v4.1.0
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.build_and_push.outputs.digest }}
        sbom-path: 'sbom.json'
        push-to-registry: true
