name: pre-commit

permissions:
  contents: read

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    env:
      PRE_COMMIT_HOME: ${{ github.workspace }}/.pre-commit

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ${{ env.PRE_COMMIT_HOME }}
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-

    - name: Run pre-commit
      run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
