name: pytest

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
    - name: Run pytest
      run: |
        uv sync
        uv run pytest --cov=src --cov-report=term-missing tests
