name: pytest

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Run pytest
      run: |
        uv venv --python 3.12
        uv pip sync requirements.txt requirements-dev.txt
        source .venv/bin/activate
        pytest --cov=src --cov-report=term-missing tests
