name: pytest

permissions:
  contents: read

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
    - name: Run pytest
      run: |
        uv sync
        uv run pytest --cov=src --cov-report=term-missing tests
