name: Verify Grandine's spec values match Vero's

permissions:
  contents: read

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/spec/configs/**.yaml"
      - "rust/grandine_bindings/**"

jobs:
  verify-spec-values-grandine:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
      - run: uvx --with pyyaml python scripts/verify_presets_rust.py
